version: '2'

services:
  spark:
    container_name: spark-master
    image: custom-spark:latest
    build:
      context: .
      dockerfile: Dockerfile.spark
    networks:
      - streaming-net
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'

  spark-worker:
    container_name: spark-worker
    image: custom-spark:latest
    build:
      context: .
      dockerfile: Dockerfile.spark
    networks:
      - streaming-net
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

networks:
  streaming-net:
    external: true